### ISSUE TITLE
Tray on Multiple Monitors

### ISSUE THREAD

**Issue by ibrokemypie** [tobi-wan-kenobi/bumblebee-status#119]
Currently on multiple monitors, at least in my case, the tray shows on the rightmost monitor, which is a fairly sensible default, however it does not seem to be configurable, unless I have missed something/ Any chance of tray position configuration, with the option of displaying it on both/all monitors?

**Comment by chrugi** [comment]
Well the tray is not part of bumblebee itself I guess.
It is configured via the config of your wm. For i3 this would be in _~/.i3/config_ or _~/.config/i3/config_.
There is (or should be) a section `bar { ... }` that defines your bar. For multiple monitors configure it so that there are different bars on each, and set the `tray_output` option according to the documentation you can find [https://i3wm.org/docs/userguide.html#_configuring_i3bar](here).

**Comment by tobi-wan-kenobi** [comment]
@chrugi is correct. The placement of the i3 status bar depends on the i3 configuration.

I can confirm that multiple monitors work, I have 3 at work ;-)

Just one addition: Actually, it's not about the `tray_output` option (this defines where the system tray with application icons, notifications, etc. shows up). To bind the i3 bar configuration to a specific monitor, you have to use the `output` directive within the `bar` section:

```
bar {
    output eDP1
}
```

You can get a list of your outputs using `xrandr`.

Cheers!
