### ISSUE TITLE
Bar becomes unclickable

### ISSUE THREAD

**Issue by RicherMans** [tobi-wan-kenobi/bumblebee-status#166]
I recently tried to use bumblebee-status and so far like it a lot!

I just noticed a problem on non-gnome DEs, which is that the bar becomes unclickable after a command could not be found. 
I run Xfce in the background, where applications such as `gnome-system-monitor` or the battery monitor do not exist.
In order to reproduce this error, simply uninstall some application e.g. gnome-system-monitor, then click on any module which opens `gnome-system-monitor`. The result is that other modules, e.g. volume, bluetooth cannot be clicked anymore.

The quick fix for this behavior is to set for each "default" key-mapping a neutral key-mapping (or none).

It's just a bit of a hassle that it is necessary to check every default keymapping for each module within the source code and remap it.

**Comment by tobi-wan-kenobi** [comment]
Glad you like it, thanks!

Yeah, that's bad. I ignored it so far, because I didn't have an idea how to nicely resolve that. Your ticket, however, inspired me:

I will implement a solution that ignores errors such as non-existent command and furthermore falls back to a global default (so that mouse-wheeling on the widgets still works, if the mouse wheel command fails, for example).

Please let me know whether the solution does what you need.
