### ISSUE TITLE
Fontawesome not loading default icons on Ubuntu 16.04

### ISSUE THREAD

**Issue by pranavsubramani** [tobi-wan-kenobi/bumblebee-status#210]
I installed powerline-fonts and added a file called fontawesome.otf to my ~/.local/share/fonts and after that, the fonts still do not display, is there a fix for this?

**Comment by tobi-wan-kenobi** [comment]
Hi,

can you please provide your `~/.i3/config` (at least the status bar config)? That would help narrow down the issue.

Thanks a lot!

**Comment by pranavsubramani** [comment]
Hey Tobi, I'm sorry, I found the answer on stack exchange, however, I am unsure as to why this line is required, you can go ahead and close the issue, but, to satiate my own curiosity, I'd love an answer:

`font pango: <myfonthere>, FontAwesome <Size>`

**Comment by tobi-wan-kenobi** [comment]
Hi,

as far as I know that is because there's actually two different types of fonts the status bar is using:
* Powerline symbols (mostly for the triangles)
* Awesome fonts (mostly for the application icons)

So, by defining FontAwesome as a fallback, you get the symbols not present in your original font. Personally, for example, I am using the font `Inconsolata`, which contains both, so I don't need a fallback.

Hope that answers your question!
