### ISSUE TITLE
Transparency?

### ISSUE THREAD

**Issue by Ubermensch85** [tobi-wan-kenobi/bumblebee-status#212]
It's possibile to implement transparency?

**Comment by tobi-wan-kenobi** [comment]
Hi,

not in `bumblebee-status` directly, and it looks like it's also not something on the i3wm roadmap.

From what I found on the net, there are 2 things you can do:

1. Make the i3bar transparent using a composite manager - with the drawback that this also makes the *text* transparent and harder to read
2. The alternative seems to be to use i3-gaps and the alpha channel in the color spec (see https://classicforum.manjaro.org/index.php?topic=27138.0)

Hope that helps!

**Comment by Ubermensch85** [comment]
I try with i3-gaps but not work

Sent from ProtonMail Mobile

Attivato mer, dic 13, 2017 alle 20:02, tobi-wan-kenobi <notifications@github.com> ha scritto:

**Comment by ltgouvea** [comment]
I tried the i3-gaps alternative without success, as well :/

**Comment by tobi-wan-kenobi** [comment]
Sorry to hear that, I haven't tried i3-gaps myself. I can give it a shot, but it'll take some time (after Christmas, probably)

Looking at https://github.com/Airblader/i3 ("Transparency"), you need to add 

```
bar {
        i3bar_command i3bar -t
}
```

Did you do that? Afterwards, you need to write your own `bumblebee-status` theme that uses RGBA colors (ie. 0xff000020 to get a pretty transparent red).

At least, that's the theory :-)

**Comment by tobi-wan-kenobi** [comment]
Short update: For me, this worked like a charm:

1. Install i3-gaps (since I'm on Fedora, I installed it from here: http://copr-fe.cloud.fedoraproject.org/coprs/gregw/i3desktop/
2. Restart i3 to get an i3-gaps session
3. In the `bar { ... }` command in question, add a line that says `i3bar_command i3bar -t`
4. Modify the theme I am using to return RGBA colors
5. Restart i3

Here's the (somewhat garish) result:
![selection_121](https://user-images.githubusercontent.com/6568442/34173578-36f9eff2-e4f6-11e7-92b0-9ef2f5658a53.png)
