### ISSUE TITLE
pasink and time icons not displaying correctly

### ISSUE THREAD

**Issue by 2secslater** [tobi-wan-kenobi/bumblebee-status#252]
Affected modules: pasink, time

Description:
Ever since the upgrade to Ubuntu Bionic, these two specific icons have been appearing like they are in the screenshot below:
https://i.imgur.com/GlkeO0p.png

I have tried resetting font cache and reinstalling the fonts (I am currently using Inconsolata).

Here's my status command:
``~/Documents/bumblebee-status/bumblebee-status -m nic bluetooth disk:home caffeine cpu memory battery spotify pasink date time -p interval=1 time.format="%H:%M:%S" date.format="%a, %b %d     %Y" home.path=/home -t kairos``

**Comment by tobi-wan-kenobi** [comment]
Hi,

I've committed a somewhat experimental ... "fix". It allows the user to select alternative iconsets by adding the `-i <iconset>` parameter to the invocation.

To test that, I've added an iconset called `ionicon`, which uses the Ionicons (http://ionicons.com/) icons - primarily because I think they look nice and they are packaged with Arch.

Note, however, that this uncovered *yet* another nasty bug: Pango (which is responsible for rendering i3bar contents) doesn't fall back to other fonts for spaces, so instead of using a "normal" whitespace, the iconset uses a somewhat wider space (otherwise, all spaces after icons would be drawn as ugly boxes).

That's not really something i3 (or any i3 bar generator) can fix, unfortunately :(

**Comment by freed00m** [comment]
> all spaces after icons would be drawn as ugly boxes
@tobi-wan-kenobi 

This happens on Sway, the wayland drop in replacement for i3wm. Maybe in future, we will have to tackle this issue. 

Would've made a screenshot but scrot didn't work on wayland ( maybe it's X app only :/ )

**Comment by tobi-wan-kenobi** [comment]
Ah, I didn't document that. You need to specify a fallback font, such as Inconsolata, for Ionicon. The reason is that the space symbol I'm using is not part of Ionicon.

⁣Sent from TypeApp ​
