### ISSUE TITLE
sensors module ignores sensors.path

### ISSUE THREAD

**Issue by ray65536** [tobi-wan-kenobi/bumblebee-status#298]
#### Summary
Affected module: sensors

Description:
If I set it to something other then default - bumblebee-status stil  reports value from default

#### How to reproduce

![image](https://user-images.githubusercontent.com/5688947/45932571-df704580-bf86-11e8-8508-bac1e845a47d.png)

#### Expected behavior

If specified sensors.path -  value from specified file expected to be used instead of the value from default file

**Comment by tobi-wan-kenobi** [comment]
Hi,

thanks for the report! I've looked into it, and it seems the sensors module uses the output of the `sensors` command, if it is available, even if you provide a sensors path to bumblebee-status; and for that to work, you need to specify `sensors.match` and `sensor.match_number`. That seems misleading, especially given that the help marks those two parameters as fallbacks.

I will modify the code so that the thermal zones are preferred, if specified in the commandline.

I'd appreciate if you could let me know whether that fixes your issue, thanks in advance!

**Comment by ray65536** [comment]
Thank you, now it works as expected.
