### ISSUE TITLE
Display lags on multiple monitors setup

### ISSUE THREAD

**Issue by sennierer** [tobi-wan-kenobi/bumblebee-status#359]
### Bug Report
When using the xrandr on a multi-monitor setup I get lagging display

#### Summary
Affected module: xrandr

#### What is the current behaviour and what is the expected behaviour?
On multi-monitors when using xrandr plugin I get display lags every 5-10 seconds.

Setup: i3 stable
bumblebee latest
arch (up to date)
X1 carbon 2017 (built in intel graphics)

**Comment by tobi-wan-kenobi** [comment]
Hi,

what do you mean by "lags"? You mean the mouse is getting unresponsive? Could that possibly be related to #280?

I am also using Arch with 2 external monitors (one HDMI, one DP), and the only lag I experience is during enabling/disabling the monitors. 

Does 'dmesg' or Xorg.log maybe give any errors?

**Comment by sennierer** [comment]
yes, sorry I somehow missed the issue. At least from the description that seems to be the same error. Short freezing of the mouse or the keyboard evrey 1-3 seconds.
I cant see any issues in Xorg or dmesg.

But I am running 4.20.6-arch1-1-ARCH.

**Comment by tobi-wan-kenobi** [comment]
Is that something you can reproduce when executing `xrandr -q`? That's the command the module uses.

I'm on 4.20.4-arch1-1-ARCH and not having the issue here (one external VGA). I'll do some more update and also check with my "bigger" setup.

Possibly it's also graphics card related, can I ask which model/driver you use?

**Comment by sennierer** [comment]
yes, when I run `xrandr -q` the same lag appears.

I use a Intel Corporation Skylake GT2 and the i915 driver.

It might also be related to my second monitor at home. Its connected via mDP to DVI. The lag does not appear when I use the Notebook screen only, but when I use the external monitor only. I have two external monitors at work connected via a dock, I'll check on Monday if the lag also appears on this setup.

Thanks for looking into this!

**Comment by tobi-wan-kenobi** [comment]
Hm, that does sound like a graphics card or driver issue.

One "workaround" I can offer: I can change the module so that it doesn't "poll" xrandr, but only does so once during startup, and then every time you switch state. That should fix the issue for you, but has one drawback: You'll only see the correct state of the monitor if you switch it on/off exclusively via bumblebee-status.

Would that be an OK intermediate solution?

**Comment by sennierer** [comment]
That would be great... Thanks!

**Comment by tobi-wan-kenobi** [comment]
Please pull in the latest changes, I hope this works around your issues.

- Default behavior is unchanged
- You can now set the parameter `xrandr.autoupdate` to `false` to disable `xrandr` polling.
- Since this makes adding/deleting displays a pain (bumblebee will not pick up on it), I added a new widget in the `xrandr` module that allows you to manually refresh the display list (and state) by clicking on it.

Example: `bumblebee-status -m xrandr -p xrandr.autoupdate=false`

Hope that helps!

**Comment by sennierer** [comment]
Great. That solved the issue. Thanks!

**Comment by sennierer** [comment]
I gave the issue another thought: Wouldnt it be possible to subscribe to the i3 output event and update the module only when the event is fired?

Something along the lines of:

```Python
import i3

i3.Subscription(update_xrandr_module, 'output')
```

**Comment by tobi-wan-kenobi** [comment]
Oh, that's a great idea! Didn't know about that capability of i3py.

**Comment by sennierer** [comment]
Thanks for implementing that. Works perfect so far!

**Comment by tobi-wan-kenobi** [comment]
Thank you for the suggestion! Glad it works!

⁣Sent from TypeApp ​
