### ISSUE TITLE
Location to not be shown in weather

### ISSUE THREAD

**Issue by kablondino** [tobi-wan-kenobi/bumblebee-status#360]
### Feature Request
Looking through the source code with my somewhat-limited python knowledge leads me to believe that you cannot toggle the location showing in the weather module.

Unless I am misunderstanding the code, could this be a toggle-able feature?

**Comment by tobi-wan-kenobi** [comment]
Yeah, that should be possible, will look into it as soon as I have enough time :)

Thanks for the suggestion!

**Comment by tobi-wan-kenobi** [comment]
Does this meet your expectations?

You can now use `bumblebee-status -m weather -p weather.location="New York,Lisbon,Munich,Stockholm" to display each of the cities.

By default, the first city is shown, and you can use left-click and right-click on the widget to cycle through.

NOTE: Every time you click, this sends a new request to the weather reporting API (by default, openweathermap.org). Please note that excessive clicking might get you blacklisted due to API rate limitations.

**Comment by kablondino** [comment]
This feature is pretty cool (and works for me), and should definitely be in here. Unfortunately, I must've not quite asked the question exactly.

I want to reduce space used by bumblebee, so I wanted the weather to just show the temperature and the symbol, but not the location. Ideally, having a list with one of the elements as blank would be awesome.

But I wanna stress that the location swapping is great and definitely needs to stay.

**Comment by tobi-wan-kenobi** [comment]
Ahhh, now I got it. What you want was already there previously, as `-p weather.showcity=false`, albeit I now see that it wasn't documented in the docstring.

I will add that, and also fix the bug with the location not being shown anymore.

Thanks for raising this!

**Comment by tobi-wan-kenobi** [comment]
Hope this matches your requirements!
