### ISSUE TITLE
Docker module documentation

### ISSUE THREAD

**Issue by sthorsen** [tobi-wan-kenobi/bumblebee-status#378]
#### Summary
Affected module: `docker`

Description:
In the documentation the module name is `docker`, but it needs to be `docker_ps` according to the code. Also the Required Python module is set to be `docker`. It is called `docker-py`

#### What is the current behaviour and what is the expected behaviour?
When using `docker` bumblebee-status fails. Using `docker_ps` it works fine

#### How to reproduce
It is easy, just use `docker` as module name at it will fail. using `docker_ps` works

#### Expected behavior
Documentation fix, nothing else

**Comment by tobi-wan-kenobi** [comment]
Thanks for the report! Always appreciate things that improve documentation, I will look into it right away.

**Comment by tobi-wan-kenobi** [comment]
Updated the module wiki page.

Regarding the required Python module: That's a tricky one, because in Python, you have to do an `import docker`, and that is what the documentation is referring to. The name of the *package* that contains the Python module "docker" changes from distro to distro, in Arch, it's called python-docker, for instance. 

For that reason, I opted to just name the Python modules in the documentation the way you would use them. Does that sound an OK approach to you?

Thanks again for raising this!

**Comment by sthorsen** [comment]
Sorry if I have been a bit unclear. It is the documentation in the wiki page: https://github.com/tobi-wan-kenobi/bumblebee-status/wiki/Available-Modules

**Comment by sthorsen** [comment]
I can see you have already updated the wiki :) Awesome
