### ISSUE TITLE
[psutil] Inaccurate data

### ISSUE THREAD

**Issue by subhrajyoti-basu** [tobi-wan-kenobi/bumblebee-status#402]
### Bug Report
Wrong resource usage showing
#### Summary
Affected module: memory

Description:
Its not actually a bug 
it mainly causing for the python module psutil
It's showing more resource usage than computer actually using

#### What is the current behavior and what is the expected behavior?
output should accurate 
can anyone one help me on writing this module where data will get fetched from htop
i think htop is a great module for near accurate results
![screenshot](https://user-images.githubusercontent.com/44311167/60279739-41e3e100-991f-11e9-8dd3-d60e523da0c9.png)
And I am new here. I am apologizing in advance if asking anything wrong.

**Comment by tobi-wan-kenobi** [comment]
Hi,

TBH, that's been a topic of ongoing debate (see #253 and #181, for example).

Right now, `memory` does not depend on psutil at all. Instead, I "manually" calculate the amount of available memory by looking at /proc/meminfo. If you show me the contents of that file on your machine, I can tell you what is going on.

Basically:
* If "MemAvailable" is present in your file (newer kernels), used memory is MemTotal - MemAvailable
* Otherwise, the used memory is MemTotal - (MemFree + Buffers + Cached + Slab)

Unfortunately, calculating free memory is not really straight-forward in Linux, as memory is only returned reluctantly, and a lot of stuff stays in various caches (that's my understanding, at least).

So maybe you have "MemAvailable", but that's not accuate for our purposes, and we need to use the fallback always.

What I am trying to do is following https://access.redhat.com/solutions/406773.

**Comment by tobi-wan-kenobi** [comment]
Also, the current output matches closely what gnome-system-monitor reports, and htop's calculation seems to be not entirely clear (see https://github.com/hishamhm/htop/issues/242). Not that htop is doing anything wrong, but with caches and buffers in user and kernel space, it seems that there's no one single answer to "how much memory is available" on a Linux system :-(

**Comment by subhrajyoti-basu** [comment]
Okey now i am realising how lame question i just asked.
Thank you for such quick response.

**Comment by tobi-wan-kenobi** [comment]
Not a lame question at all, it's something I've been struggling with *a lot* when writing the `memory` module.

Thanks for taking the time of creating an issue for this.

**Comment by somospocos** [comment]
> What I am trying to do is following https://access.redhat.com/solutions/406773.

Came here from #594

Before looking at the memory module source code, I always used to process the output of free for my pre-bumblebee era status scripts. Today, when looking at the output of /proc/meminfo, I've realized I have no clue what most of those fields mean. I find the link I've quoted above very useful. Think about adding it to the docstring of the memory module.
