### ISSUE TITLE
ALIASES_PATH

### ISSUE THREAD

**Issue by zetxx** [tobi-wan-kenobi/bumblebee-status#437]
### Bug Report
Traceback (most recent call last):
  File "/usr/bin/bumblebee-status", line 80, in <module>
    main()
  File "/usr/bin/bumblebee-status", line 51, in main
    theme=theme,
  File "/usr/share/bumblebee-status/bumblebee/engine.py", line 145, in __init__
    self._aliases = self._read_aliases()
  File "/usr/share/bumblebee-status/bumblebee/engine.py", line 239, in _read_aliases
    for name in os.listdir(ALIASES_PATH):
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/bumblebee-status/bumblebee/modules/aliases/'

#### Summary
app wont start

**Comment by tobi-wan-kenobi** [comment]
Damn :-( Are you using the git version from aur, by any chance?

⁣Sent from TypeApp ​

**Comment by zetxx** [comment]
yep

**Comment by tobi-wan-kenobi** [comment]
OK, that explains it. This is maintained by somebody else (many thanks to that person, btw!) and it probably slipped by that there's additional files required now. 

I will change the implementation today in the evening so that the aur pckage works again.

Sorry for the inconvenience! 

⁣Sent from TypeApp ​

**Comment by tobi-wan-kenobi** [comment]
Hi @zetxx ,

hope this fixes your issue & sorry for the breakage :)

**Comment by zetxx** [comment]
all good :) thanks :)
