### ISSUE TITLE
Bumblebee-status does not show the correct memory...

### ISSUE THREAD

**Issue by ReductoAdAbsurdum** [tobi-wan-kenobi/bumblebee-status#466]
#### Summary
Affected module: memory

#### Description:
The module does not show the correct memory...
htop reports 266MB of used RAM
free -m says:  used:133 shared:133 buff/cache:654
Htop is correct since used+shared=266
but bumblebee-status reports: 526Mib which doesn't seem right.

#### How to reproduce
just use the memory module.

**Comment by tobi-wan-kenobi** [comment]
Hi,

please have a look at #402, which explains the rationale behind the current calculation.

Short summary, currently, `memory` uses:

*    If "MemAvailable" is present in your file (newer kernels), used memory is MemTotal - MemAvailable
*   Otherwise, the used memory is MemTotal - (MemFree + Buffers + Cached + Slab)

Hope this helps!
