### ISSUE TITLE
Some module parameters don't seem to work

### ISSUE THREAD

**Issue by JohnDowson** [tobi-wan-kenobi/bumblebee-status#467]
pulseaudio.percent_change, pulseaudio.limit and brightness.step don't have any visible effect.

**Comment by tobi-wan-kenobi** [comment]
Hm, I wasn't able to reproduce this locally.

Which version are you using, git or one of the releases? Also, could you please specify the full bumblebee-status invocation line?

Thanks a lot in advance!

**Comment by JohnDowson** [comment]
```
status_command ~/bumblebee-status/bumblebee-status \
 -m nic sensors cpu memory battery disk pasink pasource brightness layout-xkb datetime \
 -p interval=1 \
 -t solarized-powerline
```

```
[module-parameters]
nic.states=^down
brightness.step=10
layout-xkb.showname=false
memory.format={used}
disk.format={left}
pulseaudio.autostart=true
pulseaudio.limit=100
pulseaudio.percent_change=5
datetime.format=%a, %d/%m/%y %H:%M
sensors.json=true
sensors.path=coretemp-isa-0000/Package id 0/temp1_input
```
Both git/master and the version found in AUR show this (lack of) behavior.
What `brightness` does is actually different, although i'm pretty sure this wasnt the case a week ago. It first shows brightness level adjust by +- 2%, then jumps to a multiple of 10.

On a sidenote, I find it really annoying that neither of `sensors` has a parameter to disable the frequency.

**Comment by tobi-wan-kenobi** [comment]
For pulseaudio, the answer might be that you need to specify `pasink` and `pasource` instead of `pulseaudio` in the config file.

The brightness issue is weird, nothing changed in that regards since ages, basically. Also, I cannot reproduce this behavior with the current git sources :( For me, it immediately increases/decreases by 10%. What do you mean by "it first shows brightness level adjust by 2%", you mean the first jump is by 2%, or that the value is aligned by 2%?

For sensors: ACKed, will add that when I have some spare time again.

**Comment by JohnDowson** [comment]
https://i.imgur.com/Yya1KV9.mp4
Not sure if it's very clear, but the value first goes down by 3% from 73%, then it snaps down to 63%.

**Comment by JohnDowson** [comment]
Specifying pasink and pasource solves the original issue, but there isn't really a reason as to why pulseaudio.option shouldn't work for setting both to the same value. I can't really imagine a situation where you'd want to set pasink and pasource limits to different values.

**Comment by tobi-wan-kenobi** [comment]
Full agreed, added a fix for that. Thanks for raising the issue.
