### ISSUE TITLE
Program runs with python2.7 instead of python 3.6

### ISSUE THREAD

**Issue by AurelReb** [tobi-wan-kenobi/bumblebee-status#487]
#### Description:
the program runs automatically with python 2.7 instead of python 3. 
I made an alias from python to python3 but it didn't change anything.
How can I run the program with python3 without running the command `python3 bumblebee-status`?

Thank you

**Comment by somospocos** [comment]
The header of bumblebee-status script looks like

    #!/usr/bin/env python

so it doesn't explicitly enforce python 2.

It probably happens because python on your system links to python 2. You may try using something like https://github.com/pyenv/pyenv to switch the default python on your system, but setting that up looked more time consuming to me than using the approach that you mention. What exactly the problem is with it? I have explicit

    status_command python3 /path/to/repo/bumblebee-status <arguments>

in my i3 config and it works fine.

As an option, for convenience you can wrap the python3 bumblebee-status into a shell script, save it with the same name "bumblebee-status", put it for example in ~/bin and make sure that directory is first in your PATH. With a bit of shell script voodoo you can pass the arguments to the python bumblebee script using $@.

**Comment by AurelReb** [comment]
Yes python3 before the command works. It's mainly a question about the implementation of bumblebee-status.
thanks for the shell script idea!

**Comment by brunosmmm** [comment]
Any plans to drop python 2.7 support now that it is deprecated? I see this issue with machines running Ubuntu, which unfortunately still link "python" to python2 by default.

**Comment by tobi-wan-kenobi** [comment]
In the development branch, it is dropped already.

You mean linking to python3 explicitly, right? I am of two minds regarding that, using the platform default seems the more predictable behaviour, but if it causes problems for users, then python3 is clearly the better option.
