### ISSUE TITLE
Wiki modules lacks parameters

### ISSUE THREAD

**Issue by P-Storm** [tobi-wan-kenobi/bumblebee-status#501]
### Feature Request
When searching for the parameters, I didn't see an option to find the information on the wiki. I see that there is an option list option for modules, but this is outputting for all installed modules. In PR #500 I included a filter for the commandline. Best would be to see the following 2 changes:

1. Auto publishing the parameters to the wiki
2. Auto generating the parameters. This would require rewriting the modules so that they are 'registered' at runtime.

**Comment by tobi-wan-kenobi** [comment]
Sounds interesting! I think both 1+2 require some kind of parameter "registration", which currently is not in place. The details of this are currently being discussed in #479 .

I agree, having that information in the Wiki somewhere (or in a README.md, maybe) would be nice, but I'm not sure how to go about it. Maybe just producing a markdown from bumblebee-status -l modules, so that there's a document...
