### ISSUE TITLE
Incorrect PKGBUILD for v1.9.0

### ISSUE THREAD

**Issue by flamm3blemuff1n** [tobi-wan-kenobi/bumblebee-status#510]
#### Description:
The PKGBUILD file has an incorrect pkgver and sha512sums for v1.9.0.

#### How to reproduce
```console
foo@bar:~$ wget https://github.com/tobi-wan-kenobi/bumblebee-status/archive/v1.9.0.tar.gz
foo@bar:~$ tar -xvf v1.9.0.tar.gz
foo@bar:~$ cd bumblebee-status-1.9.0
foo@bar:~$ makepkg -si
```

makepkg downloads and installs bumblebee-status-1.8.0.tar.gz!

**Comment by tobi-wan-kenobi** [comment]
RIght you are. That's a stupid mistake, because the PKGBUILD actually is in the corresponding AUR repo now.

I will just delete the PKGBUILD here to avoid further issues. Because potentially a lot of released versions are affected, however, I will *not* go through all release versions and fix the PKGBUILD.

If anyone else encounters the error, I will refer them to this issue.

Thanks a lot for raising this!
