### ISSUE TITLE
mpd module displays nothing when mpd server is not running

### ISSUE THREAD

**Issue by somospocos** [tobi-wan-kenobi/bumblebee-status#512]
#### Summary
Affected module: mpd

#### Description:
I think not displaying anything at all when mpd is not running is misleading the user. At least mpc is displaying an useful message in this situation:

    $ mpc
    mpd error: Connection refused

Suggested change: display something short but useful instead in "mpd.main" widget. For ascii theme it can be something like "[n/a] mpd". For icon theme it can be "\uf00d mpd". And add a note about this to the docstring of mpd module.

#### How to reproduce

1. make sure mpd is not running

2. run bumblebee-status -m mpd

**Comment by tobi-wan-kenobi** [comment]
Looking at the code, this seems to be intentional - if connecting to mpd fails for some reason, the widget is not shown at all.

I can change the behavior easily, I'm just not sure how to make a meaningful distinction between "the widget should show n/a" vs. "the widget should be hidden".

If it is not very important to you, I'd prefer keeping the module as it is for now.

**Comment by somospocos** [comment]
Fair enough, the widget not being shown at all has a positive aspect too - it saves some space in the bar.
