### ISSUE TITLE
pulseaudio autostart breaks the bar if pulseaudio is already running

### ISSUE THREAD

**Issue by EmmaTinten** [tobi-wan-kenobi/bumblebee-status#542]
Affected module: pulseaudio

Description:
Running the pulseaudio module with the parameter for autostarting pulseaudio loops endless if prior to starting bumblebee-status a pulseaudio process is active. 

Maybe a check for a running process should be integrated in the pulseaudio module.

**Comment by somospocos** [comment]
I don't know the development history of pulseaudio module from the beginning, but why was the autostart module parameter needed at all?

pulseaudio can run in system mode and then it is launched by system boot scripts. I am using it this way, because of specific setup, but generally, it's not recommended.

According to official docs https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Running/ pulseaudio in user mode should be able to autospawn itself, no manual intervention is needed.

**Comment by tobi-wan-kenobi** [comment]
Huh, I was counting on pulseaudio, because the documentation says it's OK to run `pulseaudio --start`, even if the daemon is already running.

And testing on my system, it works as intended - no matter how often I invoke `pulseaudio --start`, the command immediately returns and any existing pulseaudio daemons stay up.

Could you please let me know the system you're seeing the issue on?

**Comment by tobi-wan-kenobi** [comment]
@somospocos That was introduced due to #108 , where some users had issues with pulseaudio daemons not being started automagically.

@EmmaTinten If the issue really comes from this invocation, I can easily add a check, but I'd be very grateful if you could help me reproduce the issue first, by letting me know the system you're working on.

Thanks a lot in advance!

**Comment by EmmaTinten** [comment]
This did appear on a fresh installation of Fedora 31 using the XFCE Spin and then switching to i3 with bumblebee-status. I wondered why the bar does not came up and debugged it. 
An already running pulseaudio is shown in the journal:

pulseaudio[298104]: Daemon already running.

But this loops endless using the autostart parameter. Switching the parameter to not use the autostart it works. Pulseaudio is started as a systemd user unit.

Consider taking that in the Readme or enhance to exec to parse the rv of "pulseaudio --check".

**Comment by tobi-wan-kenobi** [comment]
I still find that weird, the pulseaudio documentation suggests different behaviour :(

Anyhow, @EmmaTinten , in the interest of stability, I think your suggestion makes a lot of sense.
