### ISSUE TITLE
custom i3 shortcuts to toggle module handlers

### ISSUE THREAD

**Issue by lockejan** [tobi-wan-kenobi/bumblebee-status#547]
### Feature Request

Hi,
I'd like to set a shortcut in i3wm to trigger the click events for a specific module, in my case "pomodoro".

For e.g. I want to bind mod+r to execute the left-click event on that module.
Motivation: I don't want to use my mouse but my keyboard.

Is this possible without too much hacks?

**Comment by tobi-wan-kenobi** [comment]
Now that is an interesting idea!

There are a couple of issues - the widgets you click on have auto generated (hard to guess) names, for one, and then, you can have multiple instances of bumblebee-status running at the same time, with each having multiple instances of the same modules..

So, identifying (and configuring) the correct event destination is going to be a challenge, but i have a few ideas.

Would it be ok to have to configure the mapping manually (e.g. -m date -p date.id=myid) and then trigger something like bumblebee-status-cmd myid left-mouse?

**Comment by lockejan** [comment]
Thanks for your reply.

Looks like a cool idea. Yes, this would be sufficient in my opinion.

**Comment by tobi-wan-kenobi** [comment]
OK, I'll have a go at that, time permitting. Might take a while, as this is not the "run-of-the-mill-design-in-5-minutes-code-in-20" kind of request :)

Thanks for the idea and the challenge!

**Comment by tobi-wan-kenobi** [comment]
@lockejan This is somewhat rough around the edges still, which is why I don't want to document it (yet), but:

1. Start bumblebee-status and assign IDs to widgets:
bumblebee-status -m <modules> -p <module>.id=<comma-separated list, one entry for each widget>
example: bumblebee-status -m pasink -p pasink.id=audioout

2. Use bumblebee-ctl to trigger an event:
bumblebee-ctl -i audioout -m pasink

(this defaults to left-click, you can use different events by providing --button|-b)

Please let me know whether that works for you.

Cheers!

Tobias

**Comment by lockejan** [comment]
Thanks for the quick update.
At first I missed prefixing the path to bumblebee-ctl *face-palm* :laughing: , but since changing that it's working as expected, which is fantastic.

I think that's a great new feature for bumblebee-status :+1:

**Comment by tobi-wan-kenobi** [comment]
Glad to hear it, thanks!
