### ISSUE TITLE
System module menu always goes down

### ISSUE THREAD

**Issue by rootinchase** [tobi-wan-kenobi/bumblebee-status#576]
#### Summary
Affected module: system

#### Description:
The menu for the system module goes down, and can't be configured to go up.

#### How to reproduce
1. Have your status bar on the bottom
2. Add the 'system' module to bumblebee
3. Try to operate the system module
4. Observe that it always goes down from the mouse cursor

[Screenshot](https://user-images.githubusercontent.com/19437547/77018109-4b4c2800-694a-11ea-9ff0-69b0cdd53d5b.jpg)

#### Possible Solutions
1. Add a parameter system.direction to specify
2. Have it dynamically figure out if there is enough room going down, and if there isn't, go up
3. Have it look at where the bar is (via the config), and if the bar is on the bottom, go up

**Comment by somospocos** [comment]
> Observe that it always goes down from the mouse cursor

I can't reproduce this step (I see the whole menu with the i3 bar on the bottom), but my test setup has two details:

1. I only used the system module

2. I tested on an i3/Xorg instance running inside Xephyr

For a start, I'd suggest you to do 1. as well, please try again with a minimal config, just `bumblebee-status -m system `. Most modules don't make use of Tkinter anyway, but just in case let's try to exclude the chance that it happens because system doesn't play nice with some other bumblebee-module. From my limited experience, Tkinter is smart enough to make sure that a popup menu fits on screen, so it doesn't always display it under the pixel where the mouse click event has happened.

**Comment by rootinchase** [comment]
I was fiddling around with things more, and it might be caused by how X deals with multiple monitors.

I typically have two monitors connected, a 4K monitor on the left, and a 1080p an the TOP right. and there is a black void below that monitor
![2020-03-19-1584608508_screenshot_5760x2160](https://user-images.githubusercontent.com/19437547/77049698-8c6a2980-6996-11ea-8eaf-9358ce6ebf8d.jpg)

Which is where the menu gets drawn. So, the mistake lies in the handling of multiple monitors, and how inelegant Xorg handles it.

**Comment by somospocos** [comment]
Here is some speculative (because I don't have multiple monitors to test) feedback:

I took a look at the Tk class (as in Python class) in the tkinter source and it sets default class name (as in the WM_CLASS that is displayed by xprop and used to identify windows) to 'Tk'. Perhaps you can achieve a better result by enforcing where the popup menu appears, as shown here: https://i3wm.org/docs/userguide.html#assign_workspace

**Comment by tobi-wan-kenobi** [comment]
Thanks on the detailed analysis you two!

Unfortunately, since this looks like a problem with X and multi monitor setups, I'll just close the ticket without proper resolution.
