### ISSUE TITLE
Error with pomodor.notify when using a script

### ISSUE THREAD

**Issue by Tenn4** [tobi-wan-kenobi/bumblebee-status#587]
#### Summary
Affected module: pomodoro

#### Description:
Error with pomodoro.notify when using a script as outline in issue #532 

#### How to reproduce

Following the steps in issue #532 I created a pomodoro-notify script with the following code and placed it in a Scripts folder in my home directory:
```
#!/bin/bash

notify-send -u critical "Time Up!" & tput bel
```
I then tested the script in a terminal and everything worked as expected so I inserted into the pomodo module as such: pomodoro.notify="/home/dalton/Scripts/pomodoro-notify" 

However when I ran the timer like normal (via left-click on the module) at the end of the work period it appears to have ran the script twice and not ran the bell. The "Time Up!" text pops up with the correct urgency so I know that the script is running but the bell sound doesn't play and the timer resets with 1440 minutes as the work interval.

**Comment by tobi-wan-kenobi** [comment]
Possibly, there's some issue with tput and being bound to a specific shell? But TBH, I am not sure about that, and if it works locally, it *should* work via bumblebee.

I've tried - unsuccessfully - to reproduce this. For me `tput bel` *never* outputs a bell sound, and if I replace it with a second notify-send, everything works as expected.

One think you *could* try is to write those two commands in separate lines instead of concatenating them via &. Should do the same, but emit the bell also if notifying fails for some reason.

**Comment by somospocos** [comment]
I believe the correct syntax is && not &

You can test with 

    echo "foo" & echo "bar"

vs

    echo "foo" && echo "bar"

Single & is supposed to send the command to background

**Comment by tobi-wan-kenobi** [comment]
Good catch @somospocos , didn't see that in the original question!

**Comment by Tenn4** [comment]
Thanks for the replies! I've tried both options separately (&& and separating onto two lines) and gotten the same results of it working in terminal but not once inserted into the module.  

I ran the debug flag and got this as the output: 

```
[2020-04-04 12:02:08,490] DEBUG    starting click event processing
[2020-04-04 12:03:26,013] DEBUG    new event: 
[2020-04-04 12:03:26,013] DEBUG    failed to parse event: Expecting value: line 1 column 1 (char 0)
```

I made a bit of headway by changing the bell call from `tput bel` to `echo -e "\07"` which is a bit more universal. This allowed the script to execute properly (starting the break period) but still didn't sound the bell.

**Comment by somospocos** [comment]
@tobi-wan-kenobi 

>  For me tput bel never outputs a bell sound

Same here. I get the visual bell both ways, but only if the terminal (not the shell!) supports it and has it enabled. So it doesn't work with st. But works with terminator if I enable visual bell in settings. Anyway, I don't remember exactly, but isn't this an ancient approach related to the pc speaker kernel module, that most distros/users started to disable by default at some point, because it was too annoying? I'm not even sure if my current desktop has a pc speaker at all, I've never heard it beeping during boot.

@Tenn4 

Any reason you're using tput bel / echo -e "\07" rather than just playing a sound file?

**Comment by tobi-wan-kenobi** [comment]
Ah, that *could* explain it. `bumblebee-status` is capturing/reading the output of the shell script it executes. It doesn't deal with escape sequences, so I figure it'll "swallow" the bell.

Could you maybe try piping the output into a TTY (as suggested [here](https://unix.stackexchange.com/questions/1974/how-do-i-make-my-pc-speaker-beep))?

**Comment by Tenn4** [comment]
@somospocos 

I use kitty for my terminal with the audio bell enabled to notify me of things so I figured I could use something that was already integrated instead of calling an outside program/file. I didn't realize that on most systems that would try to ring a pc speaker not a sound device via alsa, pulse, etc. 

@tobi-wan-kenobi 

At this point I was just trying to get it to work for the sake of figuring it out but, it seems like this is a pretty niche problem so I'll just close the issue and use paplay and the bell.oga file. 

Thanks for all the help!

**Comment by somospocos** [comment]
> I didn't realize that on most systems that would try to ring a pc speaker not a sound device via alsa, pulse, etc.

That was just my assumption. I think at least it used to be like that long ago, maybe even in pre-alsa era.
