### ISSUE TITLE
[RFC] State of the "development" branch

### ISSUE THREAD

**Issue by tobi-wan-kenobi** [tobi-wan-kenobi/bumblebee-status#606]
@somospocos @martindoublem @bbernhard @ibrokemypie @TheEdgeOfRage @fredj

Hello everyone,

sorry for mentioning you all together, but for some reason or another, I regard all of you as core/alpha/long-time/veteran bumblebee users and contributors.

I appreciate you might not use bumblebee anymore, and if that's the case, please feel free to stop reading.

Otherwise:

The development branch of bumblebee (significant refactoring and improvement) has matured to a point where I use it every day without issues and there's only a short list of known issues:
- deadbeef and rss haven't been migrated yet
- bumblebee-ctl hasn't been migrated yet
- some small functionality I deemed "corner case" have been dropped
- configuration file support isn't in yet

If you would like to switch to the development branch and give me some feedback on how it works for you, I would appreciate that a lot!

Many thanks in advance and thank you very much for your contributions to this tool!

**Comment by TheEdgeOfRage** [comment]
Any preferences about creating issues on the development branch? Should I just create it as a regular one or add something like [development] in the title?

**Comment by martindoublem** [comment]
Wow, thank you on seeing me as a valued user/contribtutor. I remember doing some of my first steps in python on this project.

I still use bumblebee on my daily driver and it was actually on my to-do list to switch bumblebee to development, most largely for the the interval per module which would  be great for reducing the load on my laptop on idle.

I will be sure to provide you feedback as I use it and try my best to help with issues if I can.

**Comment by tobi-wan-kenobi** [comment]
@TheEdgeOfRage good point. I'd say: [development] in the title is appreciated, and I will also add a label "development" for filtering. Hope that helps!

@martindoublem Great, thanks a lot!

**Comment by bbernhard** [comment]
Just switched to the development branch and got that: 

```
usage: bumblebee-status [-h] [-m MODULES [MODULES ...]]
                        [-p PARAMETERS [PARAMETERS ...]] [-t THEME]
                        [-i ICONSET] [-a AUTOHIDE [AUTOHIDE ...]] [--debug]
bumblebee-status: error: unrecognized arguments: -d
```

I can easily fix that, so no problems if `-d` is not supported anymore. I was just wondering if that change was intended or slipped through :)

**Comment by tobi-wan-kenobi** [comment]
damn, overlooked that one. The only thing around debugging that was intentional was that debugging into a file isn't supported anymore (since you can easily pipe, and some people had log files filling up, because they forgot to switch it off again)

**Comment by tobi-wan-kenobi** [comment]
@bbernhard fixed (yay lunchbreak :P )

Thanks for reporting! I am especially curious how your bluetooth and vpn modules work, because I had to port them "blindly", since I have no way of testing them.

**Comment by somospocos** [comment]
Good to see such a status report.

I am still using bumblebee-status, albeit not with i3. There's one particular window management thing that I can't achieve with i3 (not related to bumblebee-status at all). I don't even know if it's possible with i3. But this is offtopic for this issue. bumblebee-status has been working great for me with dwm.

This issue seems to be the right place to ask the question I had for a while. I recall you saying once that you plan to merge the development branch into master. What are your plans for master branch before merging the development branch someday? As an end user, I'd expect you to tag the last revision before the big merge and make one last stable release based on master, so those users who prefer to use the then-legacy version would have a reference git tag / source code tarball. I'm wondering about this for mercantile reasons :D, because this is my own plan as well, at least for the near future.

As for the development branch:

> some small functionality I deemed "corner case" have been dropped

I hope you don't mind me asking instead of diving up into the code in development branch, I'm a bit time constrained lately to do that. Do you have a list of those dropped features anywhere? Is my preciousss Braille graph feature one of those? I'd like to know, since I'm using it, but even if it is, this shouldn't affect any of your milestones. Once I'll switch to the development branch after it hits master, if it doesn't have support for Braille graphs, I'll probably stop using this feature for a while, then at least try to add it again on top of the new code, then you could decide if you want it back in mainline.

Regarding issues related to development branch:

> I'd say: [development] in the title is appreciated

It's good to have a consistent git history indeed, though "[development]" feels a bit long in context of a 80 chars per line constraint. Would just "[dev]" be a valid prefix? I guess I'm just being picky, not trying to stir a "[development]" vs "[dev]" holy war here, just wondering if either of those would be fine. Then one could just grep the history for "[dev" and get all of them.

**Comment by tobi-wan-kenobi** [comment]
@somospocos Yes, I am planning to do a last "stable 1.x release" with a tag, PIP and AUR package right before switching. If there's a lot of users staying on 1.x, I'll probably also do the occasional bugfix release from a 1.x branch.

Reg. the corner cases: Braille support *of course* is still there - it's one of the features I'm really proud bumblebee has, so thanks for contributing that! I don't have the list, unfortunately, because it happened gradually, it was mostly really small "special theme" handling things (like the possibility to exclude decorations such as pre and postfix on a configurational level). That was really ugly in the code, and I don't see a lot of usage scenarios for it.
And TBH, I probably dropped some thing accidentially that I implemented specifically for single bug reports. But I just had to clean up and simplify the code base.

On [development] vs [dev] - that's for ticketing only, and I am fine with both, whatever floats your boat :) In the branch itself, I am not using that at all, as the commits contain information about where they originated, so that should be good already. Hopefully :)

Thanks a lot to the feedback, everyone!

**Comment by martindoublem** [comment]
I had a question for interval, would there be a way a way of doing it so that it runs at the start and then on the top of the interval. Say for example for an interval f 1h if I start my laptop and bumblebee at 13:25, could it run then and at 14:00 and then 15;00 and so on...

The aim being if I set date at 24h, it wont miss the date change, yet wont refresh it every second.

**Comment by tobi-wan-kenobi** [comment]
@martindoublem 

Interesting idea, for that, either you just set it to 1h, that should be sufficient, or I could extend the system to have something like an "alignment" parameter :thinking:

**Comment by martindoublem** [comment]
Here is an idea, would ther be a way to give a fixed size to give a fixed size to a widget/module as to avoid them moving all the time.

**Comment by bbernhard** [comment]
> @bbernhard fixed (yay lunchbreak :P )

works again, thanks! :)

> Thanks for reporting! I am especially curious how your bluetooth and vpn modules work, because I had to port them "blindly", since I have no way of testing them.

Do you maybe mean the `pihole` module? I _think_ I haven't changed anything in the `bluetooth` module so far :thinking:

**Comment by bbernhard** [comment]
> The only thing around debugging that was intentional was that debugging into a file isn't supported anymore (since you can easily pipe, and some people had log files filling up, because they forgot to switch it off again)

Is there maybe a chance to get the "logging into a file" option somehow back? I found that one really convenient during developing - especially as it was just a single flag that I could easily set in my i3 config without changing anything else. I tried to pipe the output of bumblebee into a file, but haven't got that to work from within my i3 config.  (To be honest, I also haven't spent much time on that ;-)).

**Comment by tobi-wan-kenobi** [comment]
@bbernhard good idea - tracked in #614 

(piping the debug log should be something like `bumblebee-status -d -m cpu 2> ~/bumblebee.log`)

Ah, I confused that, I *thought* you contributed bluetooth :thinking: `pihole`, I did test, that one works for sure :)

**Comment by somospocos** [comment]
Regarding redirecting the output into a file - if it has to be done from within the i3 config, and it doesn't work by approaching it directly, it's worth trying to make use of `tee`.

**Comment by tobi-wan-kenobi** [comment]
@martindoublem Which modules are affected, in your experience? I tried to make most of the modules constant-width (I really *hate* if modules jump around).

But anyway, I agree that having an option to set the (min)width of a module/widget would make sense. It's just a bit difficult to do for a multi-widget module, as there's no way yet to specify per-widget parameters.

How about something like: `-p <module>.widget.width="2,10,5"`, maybe?

**Comment by bbernhard** [comment]
> good idea - tracked in #614

works perfect :+1: 

As we are talking about developement here: What is the current state of Python 2? Should new modules still aim to be compatible with Python 2? (Just writing a module which makes heavy use of byte operations...already a bit afraid to port that to Python 2 ;-))

**Comment by martindoublem** [comment]
Last release ever of python2 should be april normally.

**Comment by martindoublem** [comment]
Tested several modules successfully: I have an idea for one more that I might write in the next while.

**Comment by tobi-wan-kenobi** [comment]
@bbernhard @martindoublem I've decided to drop Python 2 support. It's also not included in the unit test of Travis anymore.

**Comment by tobi-wan-kenobi** [comment]
Short progress update:

1. I am *amazed* by the amount of feedback I got from you guys - many thanks!
2. What I have added over the last couple of days:
- tons of bugfixes :)
- logfile output
- dwm compatibility fields (_raw, _prefix, _suffix)
- right-to-left output
- help output (list modules/themes)
- bumblebee-ctl
3. There's only a couple of things still missing now:
- adding support for different text alignments
- adding config file support
- default handling of mouse wheel events (I find that really useful)
- finishing up documentation (have a look at `doc/` to see what I'm aiming at)

The plan is to finish those over the next 1-2 weeks, then have maybe another week or so of stabilization, and then merge to master. After that, another 1-2 weeks of gathering feedback, and once everything has calmed down, push the new version to PIP and AUR.

**Comment by somospocos** [comment]
A bit more feedback.

I have tried to run a couple of my bumblebee-status setups with the development branch (only pure i3 setups, didn't look at bridges yet) and aside from the nvidiagpu module little trouble that is already fixed, I only had to remove the --markup and --iconmarkup arguments from the bumblebee invocation command line. I do remember that the Pango voodoo went straight into theme files in development branch, hopefully you don't mind if I postpone further testing by porting the themes as well (so I fully match my config that uses master branch) closer to the big merge. I just want to avoid dealing with two branches of -contrib and bridge stuff. Since this preliminary test went well enough, I might just fully switch to the new version once it gets officially merged, if adapting the bridges won't be too time consuming. Don't want to plan too far ahead, but if I'll be happy with the transition, I might fully drop support for now-master-then-legacy branch in my -contrib and bridge repos, because I have no idea if anybody else except me is using them.

**Comment by bbernhard** [comment]
Anyone else getting those type of messages in the debug log? 

```
CRITICAL failed to import pihole: No module named 'modules.core.pihole'
CRITICAL failed to import system: No module named 'modules.core.system'
CRITICAL failed to import vpn: No module named 'modules.core.vpn'
```

The module seems to be successfully loaded though. I guess it should be modules.**contrib**.pihole, no? :thinking:

**Comment by tobi-wan-kenobi** [comment]
@somospocos 
Yes, exactly, pango is now a "real" part of the themes, I think the new implementation is substantially less hacky and more extensible (i.e. it supports *all* pango attributes).

I hope that your bridge implementation "just works", I tried to maintain backwards compatibility with that regard.

@bbernhard Good catch, that's a not-so-nice logging stemming from the fact that modules are always first looked up in `core`, then in `contrib`. Will fix that to only display errors when the module wasn't loaded at all.

**Comment by fredj** [comment]
@tobi-wan-kenobi thanks for you work on this !

**Comment by tobi-wan-kenobi** [comment]
@rad4day forgot to pull you in as well, your past contributions showed how much you care about good code, so any input from your side would be much appreciated!

**Comment by tobi-wan-kenobi** [comment]
Hopefully the last time that I am nagging all of you, but this might be of interest.

Most of you at one time or another have raised the issue of documentation (or the lack thereof, @somospocos hint hint ;) ).

I present to you my attempt at a solution:

https://bumblebee-status.readthedocs.io/en/development/

**Comment by somospocos** [comment]
I had a quick sprint over the docs.

I have no formal pull request to make, because the only thing I remember about
sphinx is the super hilarious image example from the sphinx docs.

Here are my findings:

features.html

- the last item of the list of event handler lacks a newline and the following
  line that starts with 'For example, to execute “pavucontrol”...' appears as
  part of last list item instead of being rendered after the list

- "Additional widget themeing", we'll need a native English speaker to
  confirm, but I think "theming" is correct

modules.html

- name of pulseaudio module shown as `__pulseaudio`

- multiple modules have certain parameters rendered with bold text rather than
  normal; I think the pattern for all these bold-rendered list items is that
  they contain additional text separated by newline

- cpu2.colored doc for cpu2 module still mentions --markup=pango, this option
  is gone in development branch

themes.html

- nord-powerline is not listed; I see it's gone from the development branch
  as well, while it's there in master branch

development/theme.html

- second paragraph at the top is supposed to be a list I think, it's badly
  formatted

**Comment by tobi-wan-kenobi** [comment]
@somospocos thanks for the detailed feedback, I hope I have now incorporated all your suggestions!

**Comment by martindoublem** [comment]
> @martindoublem Which modules are affected, in your experience? I tried to make most of the modules constant-width (I really _hate_ if modules jump around).
> 
> But anyway, I agree that having an option to set the (min)width of a module/widget would make sense. It's just a bit difficult to do for a multi-widget module, as there's no way yet to specify per-widget parameters.
> 
> How about something like: `-p <module>.widget.width="2,10,5"`, maybe?

nic with wifi ssid, redshift during the transation time.

**Comment by tobi-wan-kenobi** [comment]
> nic with wifi ssid, redshift during the transation time.

For redshift, I see how that happens - for NIC - what piece of the data changes?

**Comment by martindoublem** [comment]
NIC would be the SSID for wifi SSID especially if you go from a short one to a longer one.

**Comment by tobi-wan-kenobi** [comment]
@martindoublem 

At least for redshift, you can already use `redshift.theme.minwidth` to set a minimum width.

For the nic module, that might be cumbersome, since it's multi-widget. A "workaround" would be to split out the WLAN interface into a separate nic module that you give an alias and a minwidth, for example:

`-m nic:wired nic:wireless -p wired.exclude="wlp*" wireless.include="wlp*" wireless.theme.minwidth=20` or something like that (not tested), but I concede that this is pretty cumbersome.

**Comment by martindoublem** [comment]
@tobi-wan-kenobi, the recent updates I made to redshift solved that issue for me, however the same remains to be done for and or make a nic-wifi or interface.  Your idea to split the module is also good, although it does seems to be quite demanding.

**Comment by tobi-wan-kenobi** [comment]
@martindoublem how about the suggestion of using "minwidth" together with a nic config that specifically only shows wireless devices?

**Comment by tobi-wan-kenobi** [comment]
Also, here's the plan from now onwards:

- Given that I didn't get any desastrous feedback so far, I'm planning to merge development into master next friday (22nd of May). Before the merge, I'll tag and release another version of the now-stable master. Unfortunately, the maintainer of the bumblebee-status.git AUR package hasn't responded yet, so that package will probably break :(

I guess I'll be flooded by complaints from git users then :P

A week or two later, I'll do the first proper release and push it out on AUR stable and PIP.

And with that, the switch to the refactored bumblebee-status should be complete.

Let's cross fingers, and thanks a lot to the help from all of you!

**Comment by martindoublem** [comment]
> @martindoublem how about the suggestion of using "minwidth" together with a nic config that specifically only shows wireless devices?

My issue here is that I would like a maxwidth, no a minwidth. so that when I switch from a short one to a super long  it is not affected. A minwidth would be good for the other way around though.

**Comment by tobi-wan-kenobi** [comment]
> My issue here is that I would like a maxwidth, no a minwidth. so that when I switch from a short one to a super long it is not affected. A minwidth would be good for the other way around though.

Ah, now I get what you need, I think - that would be something like a generic "scrollable", right? Specify a maximum width, and if it's wider than that, start scrolling?

I think that could be doable, if that's what you need.

**Comment by martindoublem** [comment]
It is more a want than a need but it would be indeed nice!

**Comment by tobi-wan-kenobi** [comment]
@martindoublem Can you please check whether the last commit adds the functionality you're looking for:

`bumblebee-status -m spacer -p spacer.text="this is a really really long text" spacer.scrolling=true spacer.scrolling.width=4 spacer.interval=1`

works for me :)

**Comment by tobi-wan-kenobi** [comment]
just merged :fearful:

**Comment by somospocos** [comment]
Neither 0fca0bb nor v1.10.4 aren't telling me that this is the last-before-merge version. While the release note is informative about this, I expect that after a while I'll just forget the labels above. If I were you, I would just make a new branch starting with said revision with a human-friendly name like "legacy". Then switching to it for eventual bugfixes/backports would be much simpler (to me at least).

**Comment by tobi-wan-kenobi** [comment]
@somospocos 

https://bumblebee-status.readthedocs.io/en/master/FAQ.html#the-new-version-has-broken-my-setup :)

I didn't want to use something like "legacy", because I think 1.10.4 is totally fine for now - at least, until I've done the first real release from master (which is going to be 2.0.0, probably)

**Comment by somospocos** [comment]
I am not insisting on this particular branch name if that's the problem. I'd just feel more comfortable with a branch with a word label that would make it obvious switching between pre-big-merge code and after-big-merge code that is the master branch now. To me this would look consistent with how it was before the merge - we had "master" and "development" branches and didn't have to remember any numbers. Now "development" became "master", so pre-merge "master" could be codenamed somehow else. Sure I can just do this in my fork, after all a branch is just a cheap pointer to a revision.

**Comment by tobi-wan-kenobi** [comment]
Good argument, and adding tags isn't an issue :-) I'll think about a good name and add that.

**Comment by somospocos** [comment]
Thanks, it's not just a random caprice, I'm thinking about having to deal with the bridges and their interaction with the bumblebee-status code after the merge. So while 0fca0bb and v1.10.4 make sense in context of this repository, I couldn't extrapolate this naming convention there. Having a human friendly label would allow me to keep the bridge repositories consistent, as in:

- I will wait for you to pick the name for the pre-big-merge version (I really have no specific preferences as long as it will be any meaningful word)
- once I will allocate some time to work on bridges, I will sync the bumblebee-status repository, to get the latest pre-merge code
- I will check that bridges work with the newest pre-merge code
- I will just create branches with the same "legacy" name in those bridge repositories so I'll get the same branching name schema
- I will switch to master branch in both bumblebee-status (that will be post-merge code already) and bridge code and check if it works, adjust the bridge code if needed. But I'll always have that "legacy" label - the same as the one you'll choose - available to switching back and forth before pre- and post- merge in both bumblebee-status and bridge repositories

**Comment by tobi-wan-kenobi** [comment]
Got it, that makes sense.

After some thinking, I did make use of your suggestion of "legacy", the tag should now be there, pointing to the same commit as the tag v1.10.4

Cheers!
