### ISSUE TITLE
[modules/cpu2] one widget displays the wrong prefix icon

### ISSUE THREAD

**Issue by somospocos** [tobi-wan-kenobi/bumblebee-status#647]
#### Description
Affected module: cpu2
Version used: ffae9c2

test config:

    bar {
            id top
            workspace_buttons no
            # font pango:Iosevka 16
            # font pango:Terminus 16
            font pango:JetBrains Mono 16
            position top
            status_command python3 bumblebee-status \
                -m cpu2 \
                -p cpu2.layout="cpu2.cpuload" \
                -t powerline
    }

It looks like this:

![img](https://user-images.githubusercontent.com/40846997/83762557-2e7ce200-a667-11ea-8f74-54f05369b147.png)

But this is another icon, not the one specified in the vanilla file `awesome-fonts.json` from the git repository. Since I have custom themes and icons in `~/.config/bumblebee-status`, I made sure that it does not interfere with the stock files by temporarily removing that directory.

And to exclude (or at least lower down) the chance that this is a single font problem, I have tried it with at least 3 different fonts (as the commented font lines in the config above shows) with the same result.

If I remove the `-p cpu2.layout="cpu2.cpuload"` in the example above, to make the cpu2 module display all widgets by default, I am noticing that all other widgets display their icon prefixes correctly, cpuload is the only widget that misbehaves.

I ran the example above one more time, with cpu2 module displaying all widgets, and with a custom icon theme that has no powerline icons at all:

    bar {
            id top
            workspace_buttons no
            # font pango:Iosevka 16
            # font pango:Terminus 16
            font pango:JetBrains Mono 16
            position top
            status_command python3 bumblebee-status \
                -m cpu2 \
                -t powerline \
                -i char
    }

Content of `~/.config/bumblebee-status/themes/icons/char.json`:

    {
      "defaults": {
        "padding": ""
      },
      "cpu2": {
        "freq": { "prefix": "CPU" },
        "load": { "prefix": "l" },
        "loads": { "prefix": "" },
        "temp": { "prefix": "t" },
        "fan": { "prefix": "f" }
      }
    }

And guess what: that icon is still there!

![img](https://user-images.githubusercontent.com/40846997/83764921-0f338400-a66a-11ea-8d9c-87f081e960e0.png)

That's when I fired gucharmap, found that char and ran a search on the whole git repo.

And I found it. In `awesome-fonts.json`:

    "load": { "prefix": "" },

I suspect very much this is yet another name clash: as in `cpu2.load` vs `load`. Either this or the problem is here: https://github.com/tobi-wan-kenobi/bumblebee-status/blob/ffae9c2e269e3871b4479c38aafba349757b1e19/bumblebee_status/modules/contrib/cpu2.py#L61 and then it's my fault because I wrote that code. But this worked in the legacy version. And I have no idea why doesn't it work now.

**Comment by tobi-wan-kenobi** [comment]
Awesome find!

That's something that slipped in because the code for determining which "specific" theme to use just got *that* much uglier by having to factor in pango.

I covered this situation with a test now and tried to rectify the behavior. I hope that it a) works for you and b) doesn't break anything else (like other pango parts...)


gory technical details: before pango, attributes were more or less simply a depth-first search in a "theme tree" to figure out which leaf **value** fits best - and it was guaranteed that the leaf would be a plain value - a string, really. With pango,  the leave node might suddenly be a dictionary (a set of pango attributes), and it suddenly makes sense to merge different levels of "fitness". For example, the general "cpu2" module would define a font sizing/raise/whatever, and the states would define particular colors. For that, I implemented a merging algorithm, that I promptly bugged.

Thanks for discovering the bug :)
