### ISSUE TITLE
Seconds does not update for time unit

### ISSUE THREAD

**Issue by J0nnyMak0** [tobi-wan-kenobi/bumblebee-status#676]
I'm using `time.format="%H:%M:%S"`. Prior to v2 seconds used to update every second. After the update the seconds are stuck and do not update.

**Comment by tobi-wan-kenobi** [comment]
Hello,

yeah, that's a performance improvement of v2 - by default, some of the modules have larger update intervals than others.

You can work around this by adding the following parameter: `time.interval=1` *or* `time.interval=1s`.

In this particular case, however, I'd like to keep the issue open, because you shouldn't have to do this manually. The module should be smart enough to figure out when to update (or just update every second).

Also, this behaviour needs clearer documentation.

Thanks a lot for the bug report!

**Comment by JonnyMako** [comment]
Thanks for the workaround.
