### ISSUE TITLE
Unsupported locale setting and themes not working

### ISSUE THREAD

**Issue by 3301n** [tobi-wan-kenobi/bumblebee-status#803]
### Bug Report
When i set up the time module as given in the README.md 
#### Description
Affected module: <module name>time
Version used: <e.g. latest git, AUR, PIP>latest git

<description>
I setup the time and there is an error message in the status bar. Also the default themes are not working, Iam getting the same theme as i3bar
Screenshot

![github4](https://user-images.githubusercontent.com/69240615/125065494-850ce900-e0cf-11eb-906d-66ffa677f5df.png)

#### How to reproduce

1. Set up this code in my i3 config. `bar {
	status_command ~/bumblebee-status/bumblebee-status \
    -m time \   
    -p time.format="%H:%M CW %V" 
     -t default
}     `
2. Reload i3 .
3. Showing error: unsupported locale setting.

When i type locale in terminal i get this output:

`LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=`

**Comment by 3301n** [comment]
ERROR: FYI: You are using i3 version 4.19.1-non-git
ERROR: Received ConfigureNotify for unknown window 0x00800000
ERROR: Received ExposeEvent for unknown window 0x00800000
ERROR: Received ConfigureNotify for unknown window 0x00800000
ERROR: Received ConfigureNotify for unknown window 0x00800000
ERROR: Received ExposeEvent for unknown window 0x00800000
ERROR: Received ConfigureNotify for unknown window 0x00800000
ERROR: Received ConfigureNotify for unknown window 0x00800003
ERROR: Received ConfigureNotify for unknown window 0x00800003

Showing this error when i put nic in my config

**Comment by 3301n** [comment]
Finally because this repository is not user friendly and the author does not replies, I managed to find the answer myself. If anyone encountered the problem i faced in debian all you can do is follow the steps:
1. put this 2 lines in the .zshrc if you are using zsh or .bashrc if you are using bash 
`export LANGUAGE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
`
2.Enter this command in the terminal:` sudo dpkg-reconfigure locales`
3. A popup window appears. Find en_US.UTF-8 using the arrow keys . If found press the space bar. It will select that option.Press ENTER key
4. It will then probably ask for default locale. select the en_US.UTF-8 option using the arrow keys and spacebar. Press ENTER
5. It will generate the locale and it will work now. 

**I had to spend a lot of time figuring it to work. Now finally i can rest**
_If anyone encounters a problem feel free to contact me or add a comment here._

**Comment by tobi-wan-kenobi** [comment]
I usually do not do this, but I feel the need to comment on this:

This is a one-person spare-time project that is provided for free, with documentation and packaging for various distros.

You opened this issue 20h ago, and are maybe located in a different timezone than me - I think it is reasonable to afford me, the author, at least a couple of days for a response. Especially if the issue is not within the project itself, but rather a configuration issue on your system (admittedly, missing locales *should* be handled better in bumblebee)

I am happy you were able to resolve the issue, and grateful that you left instructions for others.

However, please keep in mind that open source developers habe a life outside their projects, as well, and expecting 24h support for something free is probably going to get you dissappointed. I try my best to promptly respond, but also need time to research issues, esp. if I cannot reproduce them.

Again, thank you very much for taking the time to provide your solution.

**Comment by tobi-wan-kenobi** [comment]
(to do complete justice, it is *not* a single person project, because a lot of people have contributed over time and made bumblebee so much more than I ever hoped for, but the support/issue handling is largely handled by me)

**Comment by 3301n** [comment]
Sorry for the urgency, It was mostly because of my frustration of not working out of the box. As i was new to i3. I apologize for my message as it is showing just my frustratin. Yes I admire your work. It was just a problem with my system settings that i should have solved myself rather than complaining in this github page. I love your work as it is easy to configure rather than using polybar as i had a tough time using it. Keep going.

**Comment by tobi-wan-kenobi** [comment]
Thanks for your understanding and please feel free to open more issues, if you encounter problems.
