### ISSUE TITLE
Cmus scrolling text not using available space

### ISSUE THREAD

**Issue by frdrcv** [tobi-wan-kenobi/bumblebee-status#85]
Hi,
I'm using Bumblebee with the cmus module and the scrolling text seems to use aproximately 60% of the space it's supposed to normally take, so I constantly have a black space between the text and the next arrow. I'm having this problem with Roboto Regular Font or any sans serif font; using a monospace font seems to fix it. I added two screenshots; while it seems like the text is just too short to fill the space, the artist name is "Odonis Odonis", si the text is currently scrolling. I would prefer to use a sans font, as my screen and resolution are limited.  Another problem I have is that I get really small arrows with the powerline option, whatever I use a powerline-patched font or not.

![bar1](https://cloud.githubusercontent.com/assets/7156522/26458808/5cb01eae-4142-11e7-9fb9-b16c7c411a3b.png)
![bar2](https://cloud.githubusercontent.com/assets/7156522/26458812/5f6e3180-4142-11e7-8a36-79bef7280951.png)

**Comment by tobi-wan-kenobi** [comment]
Hi,

yeah, with non-monospace fonts, that's an issue right now, because the width is calculated using "number of characters", which i3bar cannot really calculate for anything but monospace. I will look into extending the system so that you can also specify the width in pixel (will keep the issue open for this, but it might take some weeks until I get around to fixing this).

Regarding arrows: Does that also happen with the stock powerline theme? AFAICR, there's two arrows symbols in the Powerline font set that look pretty similar, but one is smaller than the other.

Thanks!

**Comment by tobi-wan-kenobi** [comment]
I looked some more into this issue, and unfortunately, it's pretty hard to fix. Essentially, for scrolling, I'm limiting the text to the number of characters available via "minwidth". With fixed-size fonts, that's straight forward, but with variable-width fonts, it's hard to calculate how many characters can be displayed. This is particularly true because I don't know the font that was configured in the i3wm configuration for that particular bar.

I'll think some more on possible solutions, but for now, I'm afraid this will have to remain an open issue.

Sorry!

**Comment by frdrcv** [comment]
Alright, thanks for giving it a look, it's really appreciated!

**Comment by tobi-wan-kenobi** [comment]
Hi,

I'm closing this issue as a "wontfix", sorry. I looked into it, but I didn't find any way to make scrolling work with non-monospaced fonts :-(

**Comment by josefbachmann** [comment]
Hello @frdrcv 
I am new to bumblebee-status. The cmus module is fantastic but I had the same problem where the field has enough space but the title doesn't use the whole space and scrolls (even with mono fonts like Liberation Mono). I just use the module _shell_ to workaround this problem. The field for the song info now got dynamic sice but always shows the whole title without scrolling. maybe that is something for you too:

the important part:

`bumblebee-status -m shell:songinfo -p songinfo.command='playerctl --player cmus metadata -f "{{xesam:artist}} - {{xesam:title}}"' songinfo.interval=1s
`
