### ISSUE TITLE
Separate module interval not working?

### ISSUE THREAD

**Issue by Zambieslar** [tobi-wan-kenobi/bumblebee-status#878]
Not sure why but separate module intervals are not working, any way to fix? 

Current config: 

bar {
    colors{
    background #373b4150
}
    status_command bumblebee-status -m cpu memory time pasink -p pasink.interval=0.1 \
            -t onedark-powerline
        i3bar_command i3bar --transparency
        position top
}

**Comment by tobi-wan-kenobi** [comment]
@Zambieslar That unfortunately is one of the non-obvious restrictions of bumblebee. The interval of a module cannot be less than the "global" interval.

And actually, the module interval needs to be a multiple of the global interval, because the global interval defines how often the bar is refreshed.

**Comment by Zambieslar** [comment]
Ahh I see. Now have the information to make this work haha! Thanks so much for getting back to me!
