### ISSUE TITLE
Scrolling status bar

### ISSUE THREAD

**Issue by HappyCthulhu** [tobi-wan-kenobi/bumblebee-status#921]
### Feature Request

I have 11 modules loaded on my status-bar. When im working on my 14" laptop, they dont have enought space. Is it possible to make statusbar, that i can scroll? Like, in left and right directions

**Comment by tobi-wan-kenobi** [comment]
This is a nice idea! (I have the same issue, but never thought of that solution)

Unfortunately, that's a bit of a bigger request, so I will have to think about how to approach that.

In the meantime, I have two workarounds that might help you:

1. All modules support "autohide", so that they only show if they are in warning/error state - this is really useful for modules such as CPU or memory. That actually shortens the bar by quite a bit, sometimes.
2. You can "minimize" modules by clicking with the middle mouse (i.e. it doesn't show the text anymore), and middle mouse again "expands" the module again.

For the long term, however, i like the idea of a scrolling bar a *lot*, thanks for the suggestion!

**Comment by tobi-wan-kenobi** [comment]
@HappyCthulhu There's a new branch now `921-scrolling-status-bar` that gives you a new module called `scroll` that you can use like this:

`-m scroll -p scroll.width=5`

This will cause the bar to have a maximum of 5 widgets, and show a module that has an arrow to the left and one to the right for scrolling.

**Comment by HappyCthulhu** [comment]
Good news. Im got tired Thinkpad, so i installed Linux on my powerfull gaming PC. That means, that i will be able to test your recent features. And i will do it in few days. 

P.S. Btw im using Arch)00)0))

**Comment by HappyCthulhu** [comment]
Nice solution! Without animation, it is not clear which modules appeared and which disappeared. But, its working, and thats is main point

> @HappyCthulhu There's a new branch now `921-scrolling-status-bar` that gives you a new module called `scroll` that you can use like this:
> 
> `-m scroll -p scroll.width=5`
> 
> This will cause the bar to have a maximum of 5 widgets, and show a module that has an arrow to the left and one to the right for scrolling.

**Comment by tobi-wan-kenobi** [comment]
Yeah, I thought about animations, but it's pretty hard, unfortunately.

**Comment by tobi-wan-kenobi** [comment]
merged into main -> this issue can be closed
