### ISSUE TITLE
Themes not loading at all

### ISSUE THREAD

**Issue by sylentpunk** [tobi-wan-kenobi/bumblebee-status#952]
#### Description
Affected module: All themes
Version used: Latest AUR 

<description>
I installed from the AUR and made sure to install font-awesome-4. When enabled in the config, no theme seems to load.

#### How to reproduce
- Download according to the instructions in the README
- Configure bar in i3config
- Reload i3 for changes to take effect
- No theme will show, instead it will only show text and vertical bars in the case of the separators.
![image](https://user-images.githubusercontent.com/111111098/220222743-4e3e9a78-7253-4189-a1fb-371cdfa3f0e6.png)

Bar config is attached below:
[config.txt](https://github.com/tobi-wan-kenobi/bumblebee-status/files/10788668/config.txt)

**Comment by tobi-wan-kenobi** [comment]
Hello!

I am pretty sure the issue is the # before -p. i3 will just send the whole statusbar command to the shell (the \ are purely cosmetic i3 config syntax), and the shell treats *everything* after the # as a comment.

Can you please try to remove the line that says "# -p \" and see if that makes a difference?

**Comment by sylentpunk** [comment]
thanks, will do when i get home and edit this comment with an update
